version: "3.3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - CHECK_RESOLVERS=true
      - MODE=swarm
      - DEFAULT_PORTS=80,443:ssl
      - DEBUG=true
      - STATS_USER=none
      - STATS_PASS=none
      - TIMEOUT_CLIENT=300
      - TIMEOUT_SERVER=300
      - TIMEOUT_CONNECT=300
      - TIMEOUT_HTTP_REQUEST=300
      - TIMEOUT_HTTP_KEEP_ALIVE=300
      - TIMEOUT_QUEUE=300
    deploy:
      mode: global

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  registry:
    image: registry:2
    ports:
      - '5000:5000'
    networks:
      - internal

  portainer:
    image: portainer/portainer
    networks:
      - proxy
      - internal
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
  internal:
    external: true
